create schema `sfp_schema`;
-- drop schema sfp_schema;
use sfp_schema;
create table company4(name varchar(10), age int, occupation varchar(6));
-- drop table company4;
insert into company4(name, age, occupation) values("rj", 23, "joks"), ("cjo", 14, "iopa");
select * from company4;
select name, age from company4;
select name from company4 where age = 23;
select * from company4;
alter table company4 add id int primary key;
select * from company4;
drop table rox;
create table rox(name varchar(10), age int, id int primary key, job varchar(8), salary int);
insert into rox(name, age, id, job, salary) values("doc", 28, 12, "boxer", 1000), ("asr", 25, 8, "police", 2000);
select * from rox;
select name from rox where salary = 1000;
select * from rox;
update rox set salary = 10000 where id = 8;
select * from rox;